//
//  StyleKitName.m
//  ProjectName
//
//  Created by 君赏 on 15/3/26.
//  Copyright (c) 2015 支付界. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Cache

static UIImage* _homeIcon = nil;
static UIImage* _homeIconSetting = nil;
static UIImage* _hommIconUser = nil;
static UIImage* _menu_list = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Images

+ (UIImage*)homeIcon { return _homeIcon ?: (_homeIcon = [UIImage imageNamed: @"homeIcon"]); }
+ (UIImage*)homeIconSetting { return _homeIconSetting ?: (_homeIconSetting = [UIImage imageNamed: @"homeIconSetting"]); }
+ (UIImage*)hommIconUser { return _hommIconUser ?: (_hommIconUser = [UIImage imageNamed: @"hommIconUser"]); }
+ (UIImage*)menu_list { return _menu_list ?: (_menu_list = [UIImage imageNamed: @"menu_list"]); }

#pragma mark Drawing Methods

+ (void)drawTagNumberButtonWithTagNumber: (NSString*)tagNumber
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color8 = [UIColor colorWithRed: 0.753 green: 0.749 blue: 0.714 alpha: 1];

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(15, 7, 50, 30);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: rectangleRect cornerRadius: 10];
    [color8 setFill];
    [rectanglePath fill];
    UIFont* rectangleFont = [UIFont systemFontOfSize: UIFont.systemFontSize];
    [UIColor.whiteColor setFill];
    CGFloat rectangleTextHeight = [tagNumber sizeWithFont: rectangleFont constrainedToSize: CGSizeMake(CGRectGetWidth(rectangleRect), INFINITY) lineBreakMode: UILineBreakModeWordWrap].height;
    CGContextSaveGState(context);
    CGContextClipToRect(context, rectangleRect);
    [tagNumber drawInRect: CGRectMake(CGRectGetMinX(rectangleRect), CGRectGetMinY(rectangleRect) + (CGRectGetHeight(rectangleRect) - rectangleTextHeight) / 2, CGRectGetWidth(rectangleRect), rectangleTextHeight) withFont: rectangleFont lineBreakMode: NSLineBreakByWordWrapping alignment: NSTextAlignmentCenter];
    CGContextRestoreGState(context);
}

+ (void)drawTagIconButtonWithFrame: (CGRect)frame
{


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.22727 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.22727 + 0.5), floor(CGRectGetWidth(frame) * 0.77273 + 0.5) - floor(CGRectGetWidth(frame) * 0.22727 + 0.5), floor(CGRectGetHeight(frame) * 0.77273 + 0.5) - floor(CGRectGetHeight(frame) * 0.22727 + 0.5));


    //// Group
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52090 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99994 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51988 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52053 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99996 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52022 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99967 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51451 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99992 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51807 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99985 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51626 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99950 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51353 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99963 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51415 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99954 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51386 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99869 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50828 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99929 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51178 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99906 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51001 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.99869 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50818 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98119 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47628 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99613 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49580 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.98990 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48478 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.50270 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01856 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.45841 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.49137 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00719 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.47572 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.45825 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00017 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.45835 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.45831 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00017 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.45825 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.06264 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.06264 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00015 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.06264 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.02812 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00015 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.02812 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.06264 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45943 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00027 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45943 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.02158 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50518 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00058 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47772 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00879 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49395 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.02135 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50543 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.54211 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98452 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.54223 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98442 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57177 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99885 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.55046 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99167 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.56054 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99675 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57317 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99908 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57221 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99896 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.57271 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99902 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57737 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99967 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57456 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99931 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.57596 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99954 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.58339 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57937 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99990 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.58135 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.63097 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97794 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.60247 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.61951 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99144 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.63099 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97798 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98511 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56138 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98509 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56133 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52090 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99438 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55044 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53634 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25011 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.08347 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16679 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12077 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25011 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.08347 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21280 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.08347 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.08347 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12077 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.12077 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.08347 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.25011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16679 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.21280 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.08347 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.25011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12077 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25011 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.25011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21280 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.21280 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25011 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];
    }
}

+ (void)drawHomeIconTagsButtonWithFrame: (CGRect)frame
{


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.20000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.17000) + 0.5, floor(CGRectGetWidth(frame) * 0.80000 + 0.5) - floor(CGRectGetWidth(frame) * 0.20000 + 0.5), floor(CGRectGetHeight(frame) * 0.83000) - floor(CGRectGetHeight(frame) * 0.17000));


    //// Group
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98226 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40511 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.87962 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31420 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.87928 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31472 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.87950 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31437 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87938 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31455 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.54258 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01650 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.50007 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.53171 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00639 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.51669 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.49991 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.50001 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.49997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.49991 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.06013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05568 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.08699 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.06013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.02500 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.50007 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05568 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98162 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48442 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98600 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47970 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98604 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47972 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.44452 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99460 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47012 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45796 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98226 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40511 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42911 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99320 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.41517 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95995 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57322 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95969 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56841 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95993 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57161 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95987 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95953 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56757 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95965 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56811 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95957 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56785 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56287 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95933 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56598 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95911 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56443 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56280 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56283 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56283 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.94195 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53445 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95629 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55180 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95031 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54200 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.48259 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12759 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.44008 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.47171 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11748 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.45670 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.43992 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11124 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.44002 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.43998 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11124 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.43992 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11110 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.06013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11110 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.06013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00014 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16677 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.02700 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00014 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13609 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16677 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51949 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00026 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51949 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.02072 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56015 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00056 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53575 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00844 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55017 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.02050 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56037 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.52043 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98624 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.52055 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98615 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.54890 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99898 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.52845 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99259 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.53812 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99715 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.55024 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99919 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.54932 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99907 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.54980 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99913 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.55428 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99970 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.55158 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99939 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.55292 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99959 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.56006 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.55620 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99991 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.55810 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.60574 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98039 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57838 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.59474 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99239 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.60576 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98043 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.94571 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61011 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.94569 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61007 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.96001 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57413 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95461 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60039 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.96001 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58785 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95995 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57322 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.96001 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57383 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57354 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33342 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.08013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25936 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.11594 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33342 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.08013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30026 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.18529 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.08013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21845 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.11594 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.18529 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.24011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25936 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.20429 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.18529 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.24011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21845 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33342 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.24011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30026 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.20429 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33342 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];
    }
}

+ (void)drawHomeAutherIconButtonWithFrame: (CGRect)frame
{


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.20000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.28000) + 0.5, floor(CGRectGetWidth(frame) * 0.80000 + 0.5) - floor(CGRectGetWidth(frame) * 0.20000 + 0.5), floor(CGRectGetHeight(frame) * 0.71000 + 0.5) - floor(CGRectGetHeight(frame) * 0.28000) - 0.5);


    //// Group
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.78170 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64263 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.69712 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.79640 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.65331 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67148 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.94071 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.79383 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98237 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.95673 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.80044 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97062 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.76847 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.78721 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99412 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.77876 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.22712 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.20287 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98237 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.21757 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.20948 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99412 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.94071 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.19625 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97062 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.95673 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.69712 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.21499 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64263 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67148 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.20029 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.65331 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.36714 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54006 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.42668 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.36273 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39423 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.39875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47543 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.37743 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.44017 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.34179 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26442 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34877 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.35363 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34179 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31036 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.34399 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22436 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34179 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25053 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34252 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23718 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.34950 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.18750 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34546 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21154 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34730 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.19925 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.40518 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05288 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.35979 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13301 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.37835 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.08814 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.49835 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.43201 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01763 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.46307 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.59316 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05449 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.53436 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.56597 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01816 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.64829 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.19231 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.62036 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09081 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.63874 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13675 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.65381 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26442 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.65197 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21902 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.65381 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.24306 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.63617 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38782 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.65381 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30716 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.64792 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.34829 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57222 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49679 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.62147 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43590 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.60015 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47222 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.63506 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54006 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.78170 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64263 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.78170 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64263 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57532 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.15491 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62420 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.17677 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58600 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.16409 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60230 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.14112 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.69712 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.14572 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64610 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.14112 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67041 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.14112 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.02756 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00772 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.89023 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.01948 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.01286 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.89931 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.85577 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00257 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.88114 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.86966 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.66026 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.01764 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61538 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63675 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00588 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62179 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.18853 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.13892 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42228 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.16795 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48184 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.15141 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45593 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.12018 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30929 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12642 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38862 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.12018 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.35096 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.13010 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22676 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12018 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.28045 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.12348 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25294 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.15711 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15865 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.13671 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20059 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.14572 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17788 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.19680 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11298 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.16850 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13942 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.18173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12420 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.24587 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.21187 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10176 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.22822 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.27894 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10417 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.25763 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.26865 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09882 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30871 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12500 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.28923 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10951 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.29915 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11645 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.28997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26442 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.29621 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16987 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.28997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21635 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30099 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37260 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.28997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30182 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.29364 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33787 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.33186 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.46635 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.30834 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40732 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.31863 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43857 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30650 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49679 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.32378 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47917 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.31533 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48932 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57532 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98236 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61538 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.66026 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99412 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62393 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63889 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.85577 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99228 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.89022 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.86966 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99742 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.88114 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.97243 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90384 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.98714 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.89931 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.98052 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90384 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.85557 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90384 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.85557 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.69712 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.84179 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62419 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.85557 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67041 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.85097 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64610 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.80485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57532 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.83260 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60230 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.82028 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58600 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.69570 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.66593 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.46314 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.68541 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49145 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.67548 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47917 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.69515 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37099 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.67843 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43536 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.68817 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40465 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.70562 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26442 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.70213 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33734 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.70562 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30182 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.70121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.19391 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.70562 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23985 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.70415 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21635 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.68798 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12821 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.69827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17147 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.69386 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14957 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.71885 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10497 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.69754 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11859 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.70783 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11084 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.75304 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.72988 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09909 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.74127 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.80265 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11298 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.77068 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.78721 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10176 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.84289 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15865 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.81808 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12420 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.83150 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13942 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.86990 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22676 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.85428 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17788 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.86329 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20059 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.87983 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30929 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.87652 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25294 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87983 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.28045 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.86108 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42067 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.87983 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.34989 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87358 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38702 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.81368 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49840 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.84859 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45433 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.83279 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48024 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98236 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61538 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98236 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61538 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];
    }
}

+ (void)drawTagImageButtonWithFrame: (CGRect)frame
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.976 green: 0.973 blue: 0.961 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 0.929 green: 0.925 blue: 0.894 alpha: 1];
    UIColor* color3 = [UIColor colorWithRed: 0.906 green: 0.902 blue: 0.859 alpha: 1];


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.00000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.00500 + 0.5), floor(CGRectGetWidth(frame) * 1.00000 + 0.5) - floor(CGRectGetWidth(frame) * 0.00000 + 0.5), floor(CGRectGetHeight(frame) * 1.00500 + 0.5) - floor(CGRectGetHeight(frame) * 0.00500 + 0.5));
    CGRect group3 = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.28571 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.23000 + 0.5), floor(CGRectGetWidth(frame) * 0.71429 + 0.5) - floor(CGRectGetWidth(frame) * 0.28571 + 0.5), floor(CGRectGetHeight(frame) * 0.59500 + 0.5) - floor(CGRectGetHeight(frame) * 0.23000 + 0.5));


    //// Group
    {
        //// Rectangle Drawing
        UIBezierPath* rectanglePath = UIBezierPath.bezierPath;
        [rectanglePath moveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [rectanglePath closePath];
        rectanglePath.lineCapStyle = kCGLineCapRound;

        [color setFill];
        [rectanglePath fill];
        [color2 setStroke];
        rectanglePath.lineWidth = 2;
        [rectanglePath stroke];
    }


    //// Group 3
    {
        //// Group 2
        {
            //// Rectangle 2 Drawing
            UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(group3) + floor(CGRectGetWidth(group3) * 0.00000 + 0.5), CGRectGetMinY(group3) + floor(CGRectGetHeight(group3) * 0.00000 + 0.5), floor(CGRectGetWidth(group3) * 1.00000 + 0.5) - floor(CGRectGetWidth(group3) * 0.00000 + 0.5), floor(CGRectGetHeight(group3) * 1.00000 + 0.5) - floor(CGRectGetHeight(group3) * 0.00000 + 0.5))];
            [color3 setStroke];
            rectangle2Path.lineWidth = 7;
            [rectangle2Path stroke];


            //// Oval Drawing
            UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(group3) + floor(CGRectGetWidth(group3) * 0.09167 + 0.5), CGRectGetMinY(group3) + floor(CGRectGetHeight(group3) * 0.19178 + 0.5), floor(CGRectGetWidth(group3) * 0.25833 + 0.5) - floor(CGRectGetWidth(group3) * 0.09167 + 0.5), floor(CGRectGetHeight(group3) * 0.46575 + 0.5) - floor(CGRectGetHeight(group3) * 0.19178 + 0.5))];
            [color3 setFill];
            [ovalPath fill];
        }


        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(group3) + 0.17917 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.82877 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.89583 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.82877 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.86250 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.51370 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.80417 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.58219 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.68750 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.36301 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.62083 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.25342 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.42083 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.65068 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.25417 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.65068 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.17917 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.82877 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.17917 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.82877 * CGRectGetHeight(group3))];
        [bezierPath closePath];
        [color3 setFill];
        [bezierPath fill];
    }


    //// Text Drawing
    CGRect textRect = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.00000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.68500 + 0.5), floor(CGRectGetWidth(frame) * 1.00000 + 0.5) - floor(CGRectGetWidth(frame) * 0.00000 + 0.5), floor(CGRectGetHeight(frame) * 0.88000 + 0.5) - floor(CGRectGetHeight(frame) * 0.68500 + 0.5));
    {
        NSString* textContent = @"为标签设置图片";
        UIFont* textFont = [UIFont systemFontOfSize: 20];
        [UIColor.blackColor setFill];
        CGFloat textTextHeight = [textContent sizeWithFont: textFont constrainedToSize: CGSizeMake(CGRectGetWidth(textRect), INFINITY) lineBreakMode: UILineBreakModeWordWrap].height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, textRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(textRect), CGRectGetMinY(textRect) + (CGRectGetHeight(textRect) - textTextHeight) / 2, CGRectGetWidth(textRect), textTextHeight) withFont: textFont lineBreakMode: NSLineBreakByWordWrapping alignment: NSTextAlignmentCenter];
        CGContextRestoreGState(context);
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfTagNumberButtonWithTagNumber: (NSString*)tagNumber
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(80, 44), NO, 0.0f);
    [StyleKitName drawTagNumberButtonWithTagNumber: tagNumber];

    UIImage* imageOfTagNumberButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTagNumberButton;
}

+ (UIImage*)imageOfTagIconButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawTagIconButtonWithFrame: frame];

    UIImage* imageOfTagIconButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTagIconButton;
}

+ (UIImage*)imageOfHomeIconTagsButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawHomeIconTagsButtonWithFrame: frame];

    UIImage* imageOfHomeIconTagsButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfHomeIconTagsButton;
}

+ (UIImage*)imageOfHomeAutherIconButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawHomeAutherIconButtonWithFrame: frame];

    UIImage* imageOfHomeAutherIconButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfHomeAutherIconButton;
}

+ (UIImage*)imageOfTagImageButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawTagImageButtonWithFrame: frame];

    UIImage* imageOfTagImageButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTagImageButton;
}

@end
