//
//  StyleKitName.h
//  ProjectName
//
//  Created by 君赏 on 15/4/3.
//  Copyright (c) 2015 支付界. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Images
+ (UIImage*)menu_list;
+ (UIImage*)homeHome;
+ (UIImage*)homeTag;
+ (UIImage*)homeAuther2;
+ (UIImage*)homeSetting;
+ (UIImage*)homeUserButtonIcon2;
+ (UIImage*)editButton;
+ (UIImage*)editMoreButton;
+ (UIImage*)backButton;
+ (UIImage*)homeRightButton;
+ (UIImage*)homeLeftButton;
+ (UIImage*)homeCellIcon;
+ (UIImage*)homeListMeIcon;
+ (UIImage*)homeListSettingIcon;
+ (UIImage*)homeListHomeIcon;
+ (UIImage*)homeListTagIcon;
+ (UIImage*)homeListUserIcon;
+ (UIImage*)tagsRightButton;
+ (UIImage*)addTagRightButton;

// Drawing Methods
+ (void)drawHomeHomeIcon;
+ (void)drawHomeTagIcon;
+ (void)drawHomeAuther;
+ (void)drawHomeSettingButtonIcon;
+ (void)drawHomeUserButtonIcon;

// Generated Images
+ (UIImage*)imageOfTagNumberButtonWithTagNumber: (NSString*)tagNumber;
+ (UIImage*)imageOfTagIconButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHomeIconTagsButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHomeAutherIconButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfTagImageButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfRolesButtonWithFrame: (CGRect)frame rolesText: (NSString*)rolesText;

@end
