//
//  StyleKitName.m
//  ProjectName
//
//  Created by 君赏 on 15/4/4.
//  Copyright (c) 2015 支付界. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Cache

static UIImage* _menu_list = nil;
static UIImage* _homeHome = nil;
static UIImage* _homeTag = nil;
static UIImage* _homeAuther2 = nil;
static UIImage* _homeSetting = nil;
static UIImage* _homeUserButtonIcon2 = nil;
static UIImage* _editButton = nil;
static UIImage* _editMoreButton = nil;
static UIImage* _backButton = nil;
static UIImage* _homeRightButton = nil;
static UIImage* _homeLeftButton = nil;
static UIImage* _homeCellIcon = nil;
static UIImage* _homeListMeIcon = nil;
static UIImage* _homeListSettingIcon = nil;
static UIImage* _homeListHomeIcon = nil;
static UIImage* _homeListTagIcon = nil;
static UIImage* _homeListUserIcon = nil;
static UIImage* _tagsRightButton = nil;
static UIImage* _addTagRightButton = nil;
static UIImage* _markdownContentRightButton = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Images

+ (UIImage*)menu_list { return _menu_list ?: (_menu_list = [UIImage imageNamed: @"menu_list"]); }
+ (UIImage*)homeHome { return _homeHome ?: (_homeHome = [UIImage imageNamed: @"homeHome"]); }
+ (UIImage*)homeTag { return _homeTag ?: (_homeTag = [UIImage imageNamed: @"homeTag"]); }
+ (UIImage*)homeAuther2 { return _homeAuther2 ?: (_homeAuther2 = [UIImage imageNamed: @"homeAuther2"]); }
+ (UIImage*)homeSetting { return _homeSetting ?: (_homeSetting = [UIImage imageNamed: @"homeSetting"]); }
+ (UIImage*)homeUserButtonIcon2 { return _homeUserButtonIcon2 ?: (_homeUserButtonIcon2 = [UIImage imageNamed: @"homeUserButtonIcon2"]); }
+ (UIImage*)editButton { return _editButton ?: (_editButton = [UIImage imageNamed: @"editButton"]); }
+ (UIImage*)editMoreButton { return _editMoreButton ?: (_editMoreButton = [UIImage imageNamed: @"editMoreButton"]); }
+ (UIImage*)backButton { return _backButton ?: (_backButton = [UIImage imageNamed: @"backButton"]); }
+ (UIImage*)homeRightButton { return _homeRightButton ?: (_homeRightButton = [UIImage imageNamed: @"homeRightButton"]); }
+ (UIImage*)homeLeftButton { return _homeLeftButton ?: (_homeLeftButton = [UIImage imageNamed: @"homeLeftButton"]); }
+ (UIImage*)homeCellIcon { return _homeCellIcon ?: (_homeCellIcon = [UIImage imageNamed: @"homeCellIcon"]); }
+ (UIImage*)homeListMeIcon { return _homeListMeIcon ?: (_homeListMeIcon = [UIImage imageNamed: @"homeListMeIcon"]); }
+ (UIImage*)homeListSettingIcon { return _homeListSettingIcon ?: (_homeListSettingIcon = [UIImage imageNamed: @"homeListSettingIcon"]); }
+ (UIImage*)homeListHomeIcon { return _homeListHomeIcon ?: (_homeListHomeIcon = [UIImage imageNamed: @"homeListHomeIcon"]); }
+ (UIImage*)homeListTagIcon { return _homeListTagIcon ?: (_homeListTagIcon = [UIImage imageNamed: @"homeListTagIcon"]); }
+ (UIImage*)homeListUserIcon { return _homeListUserIcon ?: (_homeListUserIcon = [UIImage imageNamed: @"homeListUserIcon"]); }
+ (UIImage*)tagsRightButton { return _tagsRightButton ?: (_tagsRightButton = [UIImage imageNamed: @"tagsRightButton"]); }
+ (UIImage*)addTagRightButton { return _addTagRightButton ?: (_addTagRightButton = [UIImage imageNamed: @"addTagRightButton"]); }
+ (UIImage*)markdownContentRightButton { return _markdownContentRightButton ?: (_markdownContentRightButton = [UIImage imageNamed: @"markdownContentRightButton"]); }

#pragma mark Drawing Methods

+ (void)drawTagNumberButtonWithTagNumber: (NSString*)tagNumber
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color8 = [UIColor colorWithRed: 0.188 green: 0.675 blue: 0.78 alpha: 1];

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(15, 7, 50, 30);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: rectangleRect cornerRadius: 15];
    [UIColor.whiteColor setFill];
    [rectanglePath fill];
    [color8 setStroke];
    rectanglePath.lineWidth = 0.5;
    [rectanglePath stroke];
    UIFont* rectangleFont = [UIFont systemFontOfSize: UIFont.systemFontSize];
    [color8 setFill];
    CGFloat rectangleTextHeight = [tagNumber sizeWithFont: rectangleFont constrainedToSize: CGSizeMake(CGRectGetWidth(rectangleRect), INFINITY) lineBreakMode: UILineBreakModeWordWrap].height;
    CGContextSaveGState(context);
    CGContextClipToRect(context, rectangleRect);
    [tagNumber drawInRect: CGRectMake(CGRectGetMinX(rectangleRect), CGRectGetMinY(rectangleRect) + (CGRectGetHeight(rectangleRect) - rectangleTextHeight) / 2, CGRectGetWidth(rectangleRect), rectangleTextHeight) withFont: rectangleFont lineBreakMode: NSLineBreakByWordWrapping alignment: NSTextAlignmentCenter];
    CGContextRestoreGState(context);
}

+ (void)drawTagIconButtonWithFrame: (CGRect)frame
{


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.22727 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.22727 + 0.5), floor(CGRectGetWidth(frame) * 0.77273 + 0.5) - floor(CGRectGetWidth(frame) * 0.22727 + 0.5), floor(CGRectGetHeight(frame) * 0.77273 + 0.5) - floor(CGRectGetHeight(frame) * 0.22727 + 0.5));


    //// Group
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52090 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99994 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51988 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52053 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99996 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52022 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99967 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51451 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99992 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51807 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99985 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51626 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99950 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51353 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99963 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51415 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99954 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51386 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99869 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50828 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99929 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51178 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99906 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51001 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.99869 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50818 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98119 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47628 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99613 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49580 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.98990 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48478 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.50270 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01856 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.45841 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.49137 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00719 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.47572 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.45825 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00017 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.45835 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.45831 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00017 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.45825 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.06264 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.06264 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00015 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.06264 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.02812 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00015 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.02812 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.06264 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45943 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00027 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45943 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.02158 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50518 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00058 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47772 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00879 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49395 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.02135 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50543 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.54211 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98452 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.54223 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98442 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57177 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99885 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.55046 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99167 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.56054 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99675 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57317 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99908 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57221 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99896 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.57271 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99902 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57737 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99967 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57456 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99931 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.57596 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99954 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.58339 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57937 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99990 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.58135 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.63097 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97794 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.60247 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.61951 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99144 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.63099 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97798 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98511 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56138 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98509 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56133 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52090 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99438 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55044 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53634 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25011 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.08347 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16679 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12077 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25011 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.08347 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21280 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.08347 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.08347 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12077 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.12077 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.08347 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.25011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16679 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.21280 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.08347 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.25011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12077 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16679 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25011 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.25011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21280 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.21280 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25011 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];
    }
}

+ (void)drawHomeIconTagsButtonWithFrame: (CGRect)frame
{


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.20000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.17000) + 0.5, floor(CGRectGetWidth(frame) * 0.80000 + 0.5) - floor(CGRectGetWidth(frame) * 0.20000 + 0.5), floor(CGRectGetHeight(frame) * 0.83000) - floor(CGRectGetHeight(frame) * 0.17000));


    //// Group
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98226 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40511 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.87962 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31420 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.87928 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31472 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.87950 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31437 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87938 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31455 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.54258 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01650 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.50007 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.53171 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00639 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.51669 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.49991 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.50001 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.49997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00015 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.49991 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.12012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.06013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05568 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.08699 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00013 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.06013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.02500 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.50007 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05568 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98162 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48442 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98600 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47970 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98604 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47972 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.44452 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99460 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47012 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45796 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98226 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40511 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42911 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99320 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.41517 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95995 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57322 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95969 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56841 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95993 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57161 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95987 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95953 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56757 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95965 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56811 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95957 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56785 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56287 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95933 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56598 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95911 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56443 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56280 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56283 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56283 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.94195 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53445 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95629 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55180 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95031 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54200 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.48259 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12759 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.44008 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.47171 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11748 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.45670 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.43992 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11124 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.44002 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.43998 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11124 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.43992 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11110 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.06013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11110 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.06013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00014 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16677 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.02700 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11123 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00014 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13609 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16677 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51949 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00026 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.51949 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.02072 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56015 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00056 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.53575 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00844 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.55017 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.02050 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.56037 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.52043 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98624 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.52055 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98615 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.54890 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99898 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.52845 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99259 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.53812 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99715 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.55024 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99919 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.54932 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99907 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.54980 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99913 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.55428 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99970 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.55158 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99939 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.55292 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99959 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.56006 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.55620 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99991 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.55810 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.60574 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98039 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.57838 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.59474 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99239 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.60576 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98043 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.94571 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61011 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.94569 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61007 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.96001 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57413 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.95461 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60039 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.96001 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58785 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.95995 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57322 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.96001 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57383 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.95997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57354 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33342 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.08013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25936 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.11594 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33342 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.08013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30026 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.18529 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.08013 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21845 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.11594 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.18529 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.24011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25936 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.20429 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.18529 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.24011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21845 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.16012 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33342 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.24011 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30026 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.20429 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33342 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];
    }
}

+ (void)drawHomeAutherIconButtonWithFrame: (CGRect)frame
{


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.20000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.28000) + 0.5, floor(CGRectGetWidth(frame) * 0.80000 + 0.5) - floor(CGRectGetWidth(frame) * 0.20000 + 0.5), floor(CGRectGetHeight(frame) * 0.71000 + 0.5) - floor(CGRectGetHeight(frame) * 0.28000) - 0.5);


    //// Group
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.78170 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64263 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.69712 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.79640 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.65331 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67148 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.94071 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.79383 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98237 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.80375 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.95673 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.80044 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97062 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.76847 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.78721 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99412 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.77876 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.22712 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.20287 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.98237 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.21757 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.20948 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.99412 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.94071 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.19625 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.97062 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.95673 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.69712 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.21499 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64263 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67148 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.20029 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.65331 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.36714 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54006 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.42668 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.36273 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.39423 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.39875 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47543 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.37743 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.44017 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.34179 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26442 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34877 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.35363 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34179 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.31036 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.34399 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22436 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34179 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25053 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34252 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23718 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.34950 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.18750 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.34546 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21154 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.34730 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.19925 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.40518 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05288 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.35979 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13301 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.37835 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.08814 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.49835 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.43201 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01763 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.46307 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.59316 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.05449 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.53436 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.56597 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.01816 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.64829 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.19231 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.62036 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09081 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.63874 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13675 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.65381 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26442 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.65197 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21902 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.65381 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.24306 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.63617 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38782 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.65381 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30716 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.64792 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.34829 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.57222 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49679 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.62147 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43590 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.60015 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47222 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.63506 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.54006 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.78170 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64263 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.78170 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64263 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57532 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.15491 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62420 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.17677 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58600 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.16409 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60230 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.14112 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.69712 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.14572 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64610 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.14112 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67041 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.14112 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.02756 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00772 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.89023 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.01948 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90385 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.01286 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.89931 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.85577 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00257 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.88114 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.86966 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.66026 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.01764 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61538 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63675 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.00588 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62179 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.18853 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.13892 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42228 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.16795 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48184 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.15141 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45593 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.12018 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30929 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12642 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38862 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.12018 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.35096 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.13010 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22676 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.12018 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.28045 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.12348 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25294 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.15711 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15865 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.13671 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20059 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.14572 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17788 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.19680 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11298 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.16850 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13942 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.18173 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12420 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.24587 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.21187 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10176 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.22822 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.27894 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10417 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.25763 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.26865 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09882 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30871 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12500 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.28923 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10951 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.29915 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11645 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.28997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26442 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.29621 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.16987 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.28997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21635 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30099 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37260 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.28997 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30182 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.29364 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33787 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.33186 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.46635 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.30834 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40732 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.31863 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43857 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.30650 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49679 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.32378 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47917 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.31533 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48932 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.19294 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57532 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.98236 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61538 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.66026 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.99412 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62393 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63889 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.85577 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.99228 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.89022 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.86966 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.99742 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.88114 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.97243 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90384 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.98714 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.89931 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.98052 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90384 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.85557 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.90384 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.85557 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.69712 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.84179 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.62419 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.85557 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.67041 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.85097 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.64610 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.80485 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.57532 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.83260 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.60230 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.82028 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.58600 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.69570 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50000 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.66593 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.46314 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.68541 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49145 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.67548 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.47917 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.69515 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.37099 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.67843 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.43536 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.68817 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.40465 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.70562 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.26442 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.70213 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.33734 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.70562 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30182 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.70121 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.19391 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.70562 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.23985 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.70415 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.21635 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.68798 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12821 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.69827 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17147 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.69386 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.14957 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.71885 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10497 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.69754 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11859 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.70783 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11084 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.75304 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.72988 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09909 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.74127 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.80265 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11298 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.77068 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.09615 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.78721 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.10176 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.84289 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15865 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.81808 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.12420 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.83150 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.13942 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.86990 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.22676 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.85428 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.17788 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.86329 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.20059 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.87983 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.30929 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.87652 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.25294 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87983 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.28045 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.86108 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.42067 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.87983 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.34989 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.87358 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.38702 * CGRectGetHeight(group))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.81368 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.49840 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.84859 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.45433 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.83279 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.48024 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98236 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61538 * CGRectGetHeight(group))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.98236 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.61538 * CGRectGetHeight(group))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;

        [UIColor.blackColor setFill];
        [bezier2Path fill];
    }
}

+ (void)drawTagImageButtonWithFrame: (CGRect)frame
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.976 green: 0.973 blue: 0.961 alpha: 1];
    UIColor* color2 = [UIColor colorWithRed: 0.929 green: 0.925 blue: 0.894 alpha: 1];
    UIColor* color3 = [UIColor colorWithRed: 0.906 green: 0.902 blue: 0.859 alpha: 1];


    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.00000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.00500 + 0.5), floor(CGRectGetWidth(frame) * 1.00000 + 0.5) - floor(CGRectGetWidth(frame) * 0.00000 + 0.5), floor(CGRectGetHeight(frame) * 1.00500 + 0.5) - floor(CGRectGetHeight(frame) * 0.00500 + 0.5));
    CGRect group3 = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.28571 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.23000 + 0.5), floor(CGRectGetWidth(frame) * 0.71429 + 0.5) - floor(CGRectGetWidth(frame) * 0.28571 + 0.5), floor(CGRectGetHeight(frame) * 0.59500 + 0.5) - floor(CGRectGetHeight(frame) * 0.23000 + 0.5));


    //// Group
    {
        //// Rectangle Drawing
        UIBezierPath* rectanglePath = UIBezierPath.bezierPath;
        [rectanglePath moveToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.00000 * CGRectGetHeight(group))];
        [rectanglePath closePath];
        rectanglePath.lineCapStyle = kCGLineCapRound;

        [color setFill];
        [rectanglePath fill];
        [color2 setStroke];
        rectanglePath.lineWidth = 2;
        [rectanglePath stroke];
    }


    //// Group 3
    {
        //// Group 2
        {
            //// Rectangle 2 Drawing
            UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(group3) + floor(CGRectGetWidth(group3) * 0.00000 + 0.5), CGRectGetMinY(group3) + floor(CGRectGetHeight(group3) * 0.00000 + 0.5), floor(CGRectGetWidth(group3) * 1.00000 + 0.5) - floor(CGRectGetWidth(group3) * 0.00000 + 0.5), floor(CGRectGetHeight(group3) * 1.00000 + 0.5) - floor(CGRectGetHeight(group3) * 0.00000 + 0.5))];
            [color3 setStroke];
            rectangle2Path.lineWidth = 7;
            [rectangle2Path stroke];


            //// Oval Drawing
            UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(CGRectGetMinX(group3) + floor(CGRectGetWidth(group3) * 0.09167 + 0.5), CGRectGetMinY(group3) + floor(CGRectGetHeight(group3) * 0.19178 + 0.5), floor(CGRectGetWidth(group3) * 0.25833 + 0.5) - floor(CGRectGetWidth(group3) * 0.09167 + 0.5), floor(CGRectGetHeight(group3) * 0.46575 + 0.5) - floor(CGRectGetHeight(group3) * 0.19178 + 0.5))];
            [color3 setFill];
            [ovalPath fill];
        }


        //// Bezier Drawing
        UIBezierPath* bezierPath = UIBezierPath.bezierPath;
        [bezierPath moveToPoint: CGPointMake(CGRectGetMinX(group3) + 0.17917 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.82877 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.89583 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.82877 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.86250 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.51370 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.80417 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.58219 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.68750 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.36301 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.62083 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.25342 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.42083 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.65068 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.25417 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.65068 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.17917 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.82877 * CGRectGetHeight(group3))];
        [bezierPath addLineToPoint: CGPointMake(CGRectGetMinX(group3) + 0.17917 * CGRectGetWidth(group3), CGRectGetMinY(group3) + 0.82877 * CGRectGetHeight(group3))];
        [bezierPath closePath];
        [color3 setFill];
        [bezierPath fill];
    }


    //// Text Drawing
    CGRect textRect = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.00000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.68500 + 0.5), floor(CGRectGetWidth(frame) * 1.00000 + 0.5) - floor(CGRectGetWidth(frame) * 0.00000 + 0.5), floor(CGRectGetHeight(frame) * 0.88000 + 0.5) - floor(CGRectGetHeight(frame) * 0.68500 + 0.5));
    {
        NSString* textContent = @"为标签设置图片";
        UIFont* textFont = [UIFont systemFontOfSize: 20];
        [UIColor.blackColor setFill];
        CGFloat textTextHeight = [textContent sizeWithFont: textFont constrainedToSize: CGSizeMake(CGRectGetWidth(textRect), INFINITY) lineBreakMode: UILineBreakModeWordWrap].height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, textRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(textRect), CGRectGetMinY(textRect) + (CGRectGetHeight(textRect) - textTextHeight) / 2, CGRectGetWidth(textRect), textTextHeight) withFont: textFont lineBreakMode: NSLineBreakByWordWrapping alignment: NSTextAlignmentCenter];
        CGContextRestoreGState(context);
    }
}

+ (void)drawRolesButtonWithFrame: (CGRect)frame rolesText: (NSString*)rolesText
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color8 = [UIColor colorWithRed: 0.188 green: 0.675 blue: 0.78 alpha: 1];

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.12500 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.15909 + 0.5), floor(CGRectGetWidth(frame) * 0.87500 + 0.5) - floor(CGRectGetWidth(frame) * 0.12500 + 0.5), floor(CGRectGetHeight(frame) * 0.84091 + 0.5) - floor(CGRectGetHeight(frame) * 0.15909 + 0.5));
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: rectangleRect cornerRadius: 15];
    [UIColor.whiteColor setFill];
    [rectanglePath fill];
    [color8 setStroke];
    rectanglePath.lineWidth = 0.5;
    [rectanglePath stroke];
    UIFont* rectangleFont = [UIFont systemFontOfSize: UIFont.systemFontSize];
    [color8 setFill];
    CGFloat rectangleTextHeight = [rolesText sizeWithFont: rectangleFont constrainedToSize: CGSizeMake(CGRectGetWidth(rectangleRect), INFINITY) lineBreakMode: UILineBreakModeWordWrap].height;
    CGContextSaveGState(context);
    CGContextClipToRect(context, rectangleRect);
    [rolesText drawInRect: CGRectMake(CGRectGetMinX(rectangleRect), CGRectGetMinY(rectangleRect) + (CGRectGetHeight(rectangleRect) - rectangleTextHeight) / 2, CGRectGetWidth(rectangleRect), rectangleTextHeight) withFont: rectangleFont lineBreakMode: NSLineBreakByWordWrapping alignment: NSTextAlignmentCenter];
    CGContextRestoreGState(context);
}

+ (void)drawHomeHomeIcon
{
    //// Color Declarations
    UIColor* color10 = [UIColor colorWithRed: 0.333 green: 0.431 blue: 0.475 alpha: 1];

    //// Bezier 4 Drawing
    UIBezierPath* bezier4Path = UIBezierPath.bezierPath;
    [bezier4Path moveToPoint: CGPointMake(45.46, 3.12)];
    [bezier4Path addLineToPoint: CGPointMake(8.63, 26.45)];
    [bezier4Path addLineToPoint: CGPointMake(7.5, 25.84)];
    [bezier4Path addLineToPoint: CGPointMake(44.32, 2.5)];
    [bezier4Path addLineToPoint: CGPointMake(45.46, 3.12)];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(45.96, 3.19)];
    [bezier4Path addLineToPoint: CGPointMake(82.5, 25.86)];
    [bezier4Path addLineToPoint: CGPointMake(81.34, 26.5)];
    [bezier4Path addLineToPoint: CGPointMake(44.81, 3.83)];
    [bezier4Path addLineToPoint: CGPointMake(45.96, 3.19)];
    [bezier4Path closePath];
    [color10 setStroke];
    bezier4Path.lineWidth = 3;
    [bezier4Path stroke];


    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(61.1, 39.31)];
    [bezier2Path addLineToPoint: CGPointMake(47.63, 39.31)];
    [bezier2Path addLineToPoint: CGPointMake(47.63, 52.28)];
    [bezier2Path addLineToPoint: CGPointMake(61.1, 52.28)];
    [bezier2Path addLineToPoint: CGPointMake(61.1, 39.31)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(41.24, 39.31)];
    [bezier2Path addLineToPoint: CGPointMake(27.77, 39.31)];
    [bezier2Path addLineToPoint: CGPointMake(27.77, 52.28)];
    [bezier2Path addLineToPoint: CGPointMake(41.24, 52.28)];
    [bezier2Path addCurveToPoint: CGPointMake(41.24, 45.38) controlPoint1: CGPointMake(41.24, 52.28) controlPoint2: CGPointMake(41.24, 48.76)];
    [bezier2Path addCurveToPoint: CGPointMake(41.24, 39.31) controlPoint1: CGPointMake(41.24, 42.28) controlPoint2: CGPointMake(41.24, 39.31)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(61.1, 57.06)];
    [bezier2Path addLineToPoint: CGPointMake(47.63, 57.06)];
    [bezier2Path addLineToPoint: CGPointMake(47.63, 70.03)];
    [bezier2Path addLineToPoint: CGPointMake(61.1, 70.03)];
    [bezier2Path addLineToPoint: CGPointMake(61.1, 57.06)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(41.24, 57.06)];
    [bezier2Path addLineToPoint: CGPointMake(27.77, 57.06)];
    [bezier2Path addLineToPoint: CGPointMake(27.77, 70.03)];
    [bezier2Path addLineToPoint: CGPointMake(41.24, 70.03)];
    [bezier2Path addLineToPoint: CGPointMake(41.24, 57.06)];
    [bezier2Path closePath];
    [bezier2Path moveToPoint: CGPointMake(45.15, 12)];
    [bezier2Path addCurveToPoint: CGPointMake(68.43, 26.5) controlPoint1: CGPointMake(45.15, 12) controlPoint2: CGPointMake(59.78, 21.11)];
    [bezier2Path addCurveToPoint: CGPointMake(74.63, 30.36) controlPoint1: CGPointMake(72.06, 28.76) controlPoint2: CGPointMake(74.63, 30.36)];
    [bezier2Path addLineToPoint: CGPointMake(76, 30.36)];
    [bezier2Path addLineToPoint: CGPointMake(76, 83)];
    [bezier2Path addLineToPoint: CGPointMake(15, 83)];
    [bezier2Path addLineToPoint: CGPointMake(15, 30.36)];
    [bezier2Path addLineToPoint: CGPointMake(15.66, 30.36)];
    [bezier2Path addCurveToPoint: CGPointMake(17.55, 29.18) controlPoint1: CGPointMake(15.66, 30.36) controlPoint2: CGPointMake(16.36, 29.92)];
    [bezier2Path addCurveToPoint: CGPointMake(23.07, 25.75) controlPoint1: CGPointMake(18.88, 28.35) controlPoint2: CGPointMake(20.82, 27.15)];
    [bezier2Path addCurveToPoint: CGPointMake(42.83, 13.44) controlPoint1: CGPointMake(29.57, 21.7) controlPoint2: CGPointMake(38.62, 16.06)];
    [bezier2Path addCurveToPoint: CGPointMake(45.15, 12) controlPoint1: CGPointMake(44.27, 12.54) controlPoint2: CGPointMake(45.15, 12)];
    [bezier2Path closePath];
    [color10 setFill];
    [bezier2Path fill];
}

+ (void)drawHomeTagIcon
{
    //// Color Declarations
    UIColor* color10 = [UIColor colorWithRed: 0.333 green: 0.431 blue: 0.475 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(27.13, 19.62)];
    [bezierPath addCurveToPoint: CGPointMake(24.8, 19.94) controlPoint1: CGPointMake(26.32, 19.62) controlPoint2: CGPointMake(25.54, 19.73)];
    [bezierPath addCurveToPoint: CGPointMake(18.63, 28.11) controlPoint1: CGPointMake(21.24, 20.95) controlPoint2: CGPointMake(18.63, 24.23)];
    [bezierPath addCurveToPoint: CGPointMake(27.13, 36.6) controlPoint1: CGPointMake(18.63, 32.8) controlPoint2: CGPointMake(22.44, 36.6)];
    [bezierPath addCurveToPoint: CGPointMake(35.64, 28.11) controlPoint1: CGPointMake(31.83, 36.6) controlPoint2: CGPointMake(35.64, 32.8)];
    [bezierPath addCurveToPoint: CGPointMake(27.13, 19.62) controlPoint1: CGPointMake(35.64, 23.42) controlPoint2: CGPointMake(31.83, 19.62)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(13.36, 9)];
    [bezierPath addCurveToPoint: CGPointMake(21.67, 10.9) controlPoint1: CGPointMake(13.36, 9) controlPoint2: CGPointMake(16.94, 9.82)];
    [bezierPath addCurveToPoint: CGPointMake(42.8, 15.75) controlPoint1: CGPointMake(28.93, 12.57) controlPoint2: CGPointMake(38.91, 14.85)];
    [bezierPath addCurveToPoint: CGPointMake(43.51, 15.27) controlPoint1: CGPointMake(43.26, 15.44) controlPoint2: CGPointMake(43.51, 15.27)];
    [bezierPath addCurveToPoint: CGPointMake(44.01, 16.02) controlPoint1: CGPointMake(43.51, 15.27) controlPoint2: CGPointMake(43.69, 15.54)];
    [bezierPath addCurveToPoint: CGPointMake(44.46, 16.13) controlPoint1: CGPointMake(44.3, 16.09) controlPoint2: CGPointMake(44.46, 16.13)];
    [bezierPath addCurveToPoint: CGPointMake(44.2, 16.3) controlPoint1: CGPointMake(44.46, 16.13) controlPoint2: CGPointMake(44.37, 16.19)];
    [bezierPath addCurveToPoint: CGPointMake(75.5, 62.7) controlPoint1: CGPointMake(48.85, 23.2) controlPoint2: CGPointMake(75.5, 62.7)];
    [bezierPath addLineToPoint: CGPointMake(40.21, 86.5)];
    [bezierPath addCurveToPoint: CGPointMake(8.37, 39.3) controlPoint1: CGPointMake(40.21, 86.5) controlPoint2: CGPointMake(10.78, 42.87)];
    [bezierPath addCurveToPoint: CGPointMake(8, 39.54) controlPoint1: CGPointMake(8.13, 39.46) controlPoint2: CGPointMake(8, 39.54)];
    [bezierPath addLineToPoint: CGPointMake(13.36, 9)];
    [bezierPath closePath];
    [color10 setFill];
    [bezierPath fill];


    //// Bezier 2 Drawing
    UIBezierPath* bezier2Path = UIBezierPath.bezierPath;
    [bezier2Path moveToPoint: CGPointMake(18.85, 3.39)];
    [bezier2Path addCurveToPoint: CGPointMake(48.58, 9.97) controlPoint1: CGPointMake(18.84, 3.38) controlPoint2: CGPointMake(48.58, 9.97)];
    [bezier2Path addLineToPoint: CGPointMake(81, 56.72)];
    [bezier2Path addLineToPoint: CGPointMake(77.77, 59)];
    [bezier2Path addCurveToPoint: CGPointMake(46.23, 13.52) controlPoint1: CGPointMake(77.77, 59) controlPoint2: CGPointMake(51.42, 21.01)];
    [bezier2Path addCurveToPoint: CGPointMake(18, 7.27) controlPoint1: CGPointMake(40.19, 12.18) controlPoint2: CGPointMake(18, 7.27)];
    [bezier2Path addCurveToPoint: CGPointMake(18.82, 3.49) controlPoint1: CGPointMake(18, 7.27) controlPoint2: CGPointMake(18.68, 4.12)];
    [bezier2Path addLineToPoint: CGPointMake(18.85, 3.39)];
    [bezier2Path closePath];
    [color10 setFill];
    [bezier2Path fill];
}

+ (void)drawHomeAuther
{
    //// Color Declarations
    UIColor* color10 = [UIColor colorWithRed: 0.333 green: 0.431 blue: 0.475 alpha: 1];

    //// Bezier Drawing
    UIBezierPath* bezierPath = UIBezierPath.bezierPath;
    [bezierPath moveToPoint: CGPointMake(54.43, 14.83)];
    [bezierPath addCurveToPoint: CGPointMake(55.76, 36.26) controlPoint1: CGPointMake(59.15, 20.67) controlPoint2: CGPointMake(59.6, 29.8)];
    [bezierPath addCurveToPoint: CGPointMake(66.86, 50.54) controlPoint1: CGPointMake(60.21, 41.98) controlPoint2: CGPointMake(64.93, 48.06)];
    [bezierPath addLineToPoint: CGPointMake(67.62, 50.54)];
    [bezierPath addCurveToPoint: CGPointMake(67.62, 51.52) controlPoint1: CGPointMake(67.62, 50.54) controlPoint2: CGPointMake(67.62, 50.89)];
    [bezierPath addCurveToPoint: CGPointMake(67.76, 51.7) controlPoint1: CGPointMake(67.71, 51.64) controlPoint2: CGPointMake(67.76, 51.7)];
    [bezierPath addLineToPoint: CGPointMake(67.62, 51.7)];
    [bezierPath addCurveToPoint: CGPointMake(67.62, 79.5) controlPoint1: CGPointMake(67.62, 57.1) controlPoint2: CGPointMake(67.62, 79.5)];
    [bezierPath addLineToPoint: CGPointMake(24.7, 79.5)];
    [bezierPath addCurveToPoint: CGPointMake(24.7, 51.7) controlPoint1: CGPointMake(24.7, 79.5) controlPoint2: CGPointMake(24.7, 57.1)];
    [bezierPath addLineToPoint: CGPointMake(24.56, 51.7)];
    [bezierPath addCurveToPoint: CGPointMake(24.7, 51.52) controlPoint1: CGPointMake(24.56, 51.7) controlPoint2: CGPointMake(24.61, 51.64)];
    [bezierPath addCurveToPoint: CGPointMake(24.7, 50.54) controlPoint1: CGPointMake(24.7, 50.89) controlPoint2: CGPointMake(24.7, 50.54)];
    [bezierPath addLineToPoint: CGPointMake(25.46, 50.54)];
    [bezierPath addCurveToPoint: CGPointMake(35.32, 37.86) controlPoint1: CGPointMake(27.21, 48.29) controlPoint2: CGPointMake(31.26, 43.08)];
    [bezierPath addCurveToPoint: CGPointMake(33.3, 18.57) controlPoint1: CGPointMake(31.25, 32.55) controlPoint2: CGPointMake(30.57, 24.72)];
    [bezierPath addCurveToPoint: CGPointMake(35.57, 14.83) controlPoint1: CGPointMake(33.89, 17.23) controlPoint2: CGPointMake(34.65, 15.97)];
    [bezierPath addCurveToPoint: CGPointMake(54.43, 14.83) controlPoint1: CGPointMake(40.78, 8.39) controlPoint2: CGPointMake(49.22, 8.39)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(70.67, 14.83)];
    [bezierPath addCurveToPoint: CGPointMake(72, 36.26) controlPoint1: CGPointMake(75.39, 20.67) controlPoint2: CGPointMake(75.84, 29.8)];
    [bezierPath addCurveToPoint: CGPointMake(83.1, 50.54) controlPoint1: CGPointMake(76.45, 41.98) controlPoint2: CGPointMake(81.17, 48.06)];
    [bezierPath addLineToPoint: CGPointMake(83.86, 50.54)];
    [bezierPath addCurveToPoint: CGPointMake(83.86, 51.52) controlPoint1: CGPointMake(83.86, 50.54) controlPoint2: CGPointMake(83.86, 50.89)];
    [bezierPath addCurveToPoint: CGPointMake(84, 51.7) controlPoint1: CGPointMake(83.95, 51.64) controlPoint2: CGPointMake(84, 51.7)];
    [bezierPath addLineToPoint: CGPointMake(83.86, 51.7)];
    [bezierPath addCurveToPoint: CGPointMake(83.86, 79.5) controlPoint1: CGPointMake(83.86, 57.1) controlPoint2: CGPointMake(83.86, 79.5)];
    [bezierPath addLineToPoint: CGPointMake(68.78, 79.5)];
    [bezierPath addCurveToPoint: CGPointMake(68.78, 51.7) controlPoint1: CGPointMake(68.78, 79.5) controlPoint2: CGPointMake(68.78, 57.1)];
    [bezierPath addLineToPoint: CGPointMake(68.92, 51.7)];
    [bezierPath addCurveToPoint: CGPointMake(68.78, 51.52) controlPoint1: CGPointMake(68.92, 51.7) controlPoint2: CGPointMake(68.87, 51.64)];
    [bezierPath addCurveToPoint: CGPointMake(68.78, 50.54) controlPoint1: CGPointMake(68.78, 50.89) controlPoint2: CGPointMake(68.78, 50.54)];
    [bezierPath addLineToPoint: CGPointMake(68.02, 50.54)];
    [bezierPath addCurveToPoint: CGPointMake(56.92, 36.26) controlPoint1: CGPointMake(66.09, 48.06) controlPoint2: CGPointMake(61.37, 41.98)];
    [bezierPath addCurveToPoint: CGPointMake(55.59, 14.83) controlPoint1: CGPointMake(60.76, 29.8) controlPoint2: CGPointMake(60.31, 20.67)];
    [bezierPath addCurveToPoint: CGPointMake(53.7, 12.89) controlPoint1: CGPointMake(55, 14.1) controlPoint2: CGPointMake(54.37, 13.45)];
    [bezierPath addCurveToPoint: CGPointMake(70.67, 14.83) controlPoint1: CGPointMake(58.9, 8.47) controlPoint2: CGPointMake(66.06, 9.12)];
    [bezierPath closePath];
    [bezierPath moveToPoint: CGPointMake(27.54, 10.06)];
    [bezierPath addCurveToPoint: CGPointMake(35.14, 13.99) controlPoint1: CGPointMake(30.27, 10.33) controlPoint2: CGPointMake(32.94, 11.65)];
    [bezierPath addCurveToPoint: CGPointMake(34.41, 14.83) controlPoint1: CGPointMake(34.89, 14.26) controlPoint2: CGPointMake(34.64, 14.54)];
    [bezierPath addCurveToPoint: CGPointMake(32.14, 18.57) controlPoint1: CGPointMake(33.49, 15.97) controlPoint2: CGPointMake(32.73, 17.23)];
    [bezierPath addCurveToPoint: CGPointMake(34.16, 37.86) controlPoint1: CGPointMake(29.41, 24.72) controlPoint2: CGPointMake(30.09, 32.55)];
    [bezierPath addCurveToPoint: CGPointMake(24.3, 50.54) controlPoint1: CGPointMake(30.1, 43.08) controlPoint2: CGPointMake(26.05, 48.29)];
    [bezierPath addLineToPoint: CGPointMake(23.54, 50.54)];
    [bezierPath addCurveToPoint: CGPointMake(23.54, 51.52) controlPoint1: CGPointMake(23.54, 50.54) controlPoint2: CGPointMake(23.54, 50.89)];
    [bezierPath addCurveToPoint: CGPointMake(23.4, 51.7) controlPoint1: CGPointMake(23.45, 51.64) controlPoint2: CGPointMake(23.4, 51.7)];
    [bezierPath addLineToPoint: CGPointMake(23.54, 51.7)];
    [bezierPath addCurveToPoint: CGPointMake(23.54, 79.5) controlPoint1: CGPointMake(23.54, 57.1) controlPoint2: CGPointMake(23.54, 79.5)];
    [bezierPath addLineToPoint: CGPointMake(6.14, 79.5)];
    [bezierPath addCurveToPoint: CGPointMake(6.14, 51.7) controlPoint1: CGPointMake(6.14, 79.5) controlPoint2: CGPointMake(6.14, 57.1)];
    [bezierPath addLineToPoint: CGPointMake(6, 51.7)];
    [bezierPath addCurveToPoint: CGPointMake(6.14, 51.52) controlPoint1: CGPointMake(6, 51.7) controlPoint2: CGPointMake(6.05, 51.64)];
    [bezierPath addCurveToPoint: CGPointMake(6.14, 50.54) controlPoint1: CGPointMake(6.14, 50.89) controlPoint2: CGPointMake(6.14, 50.54)];
    [bezierPath addLineToPoint: CGPointMake(6.9, 50.54)];
    [bezierPath addCurveToPoint: CGPointMake(16.75, 37.86) controlPoint1: CGPointMake(8.65, 48.29) controlPoint2: CGPointMake(12.7, 43.08)];
    [bezierPath addCurveToPoint: CGPointMake(14.74, 18.57) controlPoint1: CGPointMake(12.69, 32.55) controlPoint2: CGPointMake(12.01, 24.72)];
    [bezierPath addCurveToPoint: CGPointMake(17.01, 14.83) controlPoint1: CGPointMake(15.33, 17.23) controlPoint2: CGPointMake(16.09, 15.97)];
    [bezierPath addCurveToPoint: CGPointMake(27.54, 10.06) controlPoint1: CGPointMake(19.89, 11.27) controlPoint2: CGPointMake(23.77, 9.67)];
    [bezierPath closePath];
    [color10 setFill];
    [bezierPath fill];
}

+ (void)drawHomeSettingButtonIcon
{
    //// Color Declarations
    UIColor* color10 = [UIColor colorWithRed: 0.333 green: 0.431 blue: 0.475 alpha: 1];

    //// Bezier 7 Drawing
    UIBezierPath* bezier7Path = UIBezierPath.bezierPath;
    [bezier7Path moveToPoint: CGPointMake(48.56, 3.5)];
    [bezier7Path addCurveToPoint: CGPointMake(51.39, 15.21) controlPoint1: CGPointMake(48.56, 3.5) controlPoint2: CGPointMake(50.47, 11.4)];
    [bezier7Path addCurveToPoint: CGPointMake(62.83, 21.02) controlPoint1: CGPointMake(55.67, 16.27) controlPoint2: CGPointMake(59.56, 18.29)];
    [bezier7Path addCurveToPoint: CGPointMake(75.64, 16.96) controlPoint1: CGPointMake(64.31, 20.55) controlPoint2: CGPointMake(75.64, 16.96)];
    [bezier7Path addLineToPoint: CGPointMake(80, 23.98)];
    [bezier7Path addCurveToPoint: CGPointMake(71.3, 32.91) controlPoint1: CGPointMake(80, 23.98) controlPoint2: CGPointMake(73.55, 30.6)];
    [bezier7Path addCurveToPoint: CGPointMake(73.11, 42.94) controlPoint1: CGPointMake(72.47, 36.03) controlPoint2: CGPointMake(73.11, 39.41)];
    [bezier7Path addCurveToPoint: CGPointMake(71.89, 51.21) controlPoint1: CGPointMake(73.11, 45.82) controlPoint2: CGPointMake(72.68, 48.59)];
    [bezier7Path addCurveToPoint: CGPointMake(79.93, 61.7) controlPoint1: CGPointMake(73.19, 52.92) controlPoint2: CGPointMake(79.93, 61.7)];
    [bezier7Path addLineToPoint: CGPointMake(74.77, 68.16)];
    [bezier7Path addCurveToPoint: CGPointMake(64.38, 63.46) controlPoint1: CGPointMake(74.77, 68.16) controlPoint2: CGPointMake(67.89, 65.05)];
    [bezier7Path addCurveToPoint: CGPointMake(50.52, 70.87) controlPoint1: CGPointMake(60.61, 67.11) controlPoint2: CGPointMake(55.84, 69.72)];
    [bezier7Path addCurveToPoint: CGPointMake(47.21, 82.5) controlPoint1: CGPointMake(49.56, 74.24) controlPoint2: CGPointMake(47.21, 82.5)];
    [bezier7Path addLineToPoint: CGPointMake(38.92, 82.25)];
    [bezier7Path addCurveToPoint: CGPointMake(36.3, 70.36) controlPoint1: CGPointMake(38.92, 82.25) controlPoint2: CGPointMake(37.04, 73.73)];
    [bezier7Path addCurveToPoint: CGPointMake(27.23, 65.82) controlPoint1: CGPointMake(32.99, 69.39) controlPoint2: CGPointMake(29.93, 67.84)];
    [bezier7Path addCurveToPoint: CGPointMake(17.83, 70.56) controlPoint1: CGPointMake(23.65, 67.63) controlPoint2: CGPointMake(17.83, 70.56)];
    [bezier7Path addLineToPoint: CGPointMake(12.4, 64.32)];
    [bezier7Path addCurveToPoint: CGPointMake(18.62, 55.46) controlPoint1: CGPointMake(12.4, 64.32) controlPoint2: CGPointMake(16.34, 58.71)];
    [bezier7Path addCurveToPoint: CGPointMake(15.73, 42.94) controlPoint1: CGPointMake(16.77, 51.68) controlPoint2: CGPointMake(15.73, 47.43)];
    [bezier7Path addCurveToPoint: CGPointMake(17.85, 32.13) controlPoint1: CGPointMake(15.73, 39.11) controlPoint2: CGPointMake(16.48, 35.46)];
    [bezier7Path addCurveToPoint: CGPointMake(10.06, 21.85) controlPoint1: CGPointMake(16.2, 29.95) controlPoint2: CGPointMake(10.06, 21.85)];
    [bezier7Path addCurveToPoint: CGPointMake(14.64, 16.19) controlPoint1: CGPointMake(10.06, 21.85) controlPoint2: CGPointMake(13.26, 17.9)];
    [bezier7Path addCurveToPoint: CGPointMake(15.26, 15.42) controlPoint1: CGPointMake(15.02, 15.72) controlPoint2: CGPointMake(15.26, 15.42)];
    [bezier7Path addCurveToPoint: CGPointMake(26.53, 20.59) controlPoint1: CGPointMake(15.26, 15.42) controlPoint2: CGPointMake(23.52, 19.21)];
    [bezier7Path addCurveToPoint: CGPointMake(30.48, 17.96) controlPoint1: CGPointMake(27.77, 19.61) controlPoint2: CGPointMake(29.09, 18.73)];
    [bezier7Path addCurveToPoint: CGPointMake(31, 17.67) controlPoint1: CGPointMake(30.65, 17.86) controlPoint2: CGPointMake(30.83, 17.76)];
    [bezier7Path addCurveToPoint: CGPointMake(32.32, 17.02) controlPoint1: CGPointMake(31.44, 17.44) controlPoint2: CGPointMake(31.88, 17.22)];
    [bezier7Path addCurveToPoint: CGPointMake(37.45, 15.21) controlPoint1: CGPointMake(33.95, 16.26) controlPoint2: CGPointMake(35.67, 15.65)];
    [bezier7Path addCurveToPoint: CGPointMake(38.17, 12.22) controlPoint1: CGPointMake(37.65, 14.37) controlPoint2: CGPointMake(37.9, 13.33)];
    [bezier7Path addCurveToPoint: CGPointMake(40.28, 3.5) controlPoint1: CGPointMake(39.12, 8.29) controlPoint2: CGPointMake(40.28, 3.5)];
    [bezier7Path addLineToPoint: CGPointMake(48.56, 3.5)];
    [bezier7Path addLineToPoint: CGPointMake(48.56, 3.5)];
    [bezier7Path closePath];
    [bezier7Path moveToPoint: CGPointMake(44.42, 37.22)];
    [bezier7Path addCurveToPoint: CGPointMake(43.67, 37.27) controlPoint1: CGPointMake(44.16, 37.22) controlPoint2: CGPointMake(43.91, 37.24)];
    [bezier7Path addCurveToPoint: CGPointMake(38.68, 42.94) controlPoint1: CGPointMake(40.85, 37.64) controlPoint2: CGPointMake(38.68, 40.04)];
    [bezier7Path addCurveToPoint: CGPointMake(44.42, 48.66) controlPoint1: CGPointMake(38.68, 46.1) controlPoint2: CGPointMake(41.25, 48.66)];
    [bezier7Path addCurveToPoint: CGPointMake(50.16, 42.94) controlPoint1: CGPointMake(47.59, 48.66) controlPoint2: CGPointMake(50.16, 46.1)];
    [bezier7Path addCurveToPoint: CGPointMake(44.42, 37.22) controlPoint1: CGPointMake(50.16, 39.78) controlPoint2: CGPointMake(47.59, 37.22)];
    [bezier7Path closePath];
    [bezier7Path moveToPoint: CGPointMake(53.99, 33.32)];
    [bezier7Path addCurveToPoint: CGPointMake(53.99, 53.13) controlPoint1: CGPointMake(59.59, 38.79) controlPoint2: CGPointMake(59.59, 47.66)];
    [bezier7Path addCurveToPoint: CGPointMake(33.7, 53.13) controlPoint1: CGPointMake(48.39, 58.6) controlPoint2: CGPointMake(39.3, 58.6)];
    [bezier7Path addCurveToPoint: CGPointMake(33.6, 33.43) controlPoint1: CGPointMake(28.14, 47.69) controlPoint2: CGPointMake(28.1, 38.9)];
    [bezier7Path addLineToPoint: CGPointMake(33.7, 33.32)];
    [bezier7Path addCurveToPoint: CGPointMake(36.61, 31.13) controlPoint1: CGPointMake(34.59, 32.45) controlPoint2: CGPointMake(35.57, 31.72)];
    [bezier7Path addCurveToPoint: CGPointMake(53.99, 33.32) controlPoint1: CGPointMake(42.1, 27.99) controlPoint2: CGPointMake(49.28, 28.72)];
    [bezier7Path closePath];
    [bezier7Path moveToPoint: CGPointMake(44.71, 23.51)];
    [bezier7Path addCurveToPoint: CGPointMake(40.5, 23.95) controlPoint1: CGPointMake(43.26, 23.51) controlPoint2: CGPointMake(41.85, 23.66)];
    [bezier7Path addCurveToPoint: CGPointMake(37.48, 24.86) controlPoint1: CGPointMake(39.46, 24.18) controlPoint2: CGPointMake(38.45, 24.48)];
    [bezier7Path addCurveToPoint: CGPointMake(32.46, 27.73) controlPoint1: CGPointMake(35.66, 25.57) controlPoint2: CGPointMake(33.97, 26.54)];
    [bezier7Path addCurveToPoint: CGPointMake(24.91, 43.23) controlPoint1: CGPointMake(27.86, 31.34) controlPoint2: CGPointMake(24.91, 36.94)];
    [bezier7Path addCurveToPoint: CGPointMake(44.71, 62.94) controlPoint1: CGPointMake(24.91, 54.12) controlPoint2: CGPointMake(33.77, 62.94)];
    [bezier7Path addCurveToPoint: CGPointMake(64.5, 43.23) controlPoint1: CGPointMake(55.64, 62.94) controlPoint2: CGPointMake(64.5, 54.12)];
    [bezier7Path addCurveToPoint: CGPointMake(63.77, 37.89) controlPoint1: CGPointMake(64.5, 41.38) controlPoint2: CGPointMake(64.25, 39.59)];
    [bezier7Path addCurveToPoint: CGPointMake(44.71, 23.51) controlPoint1: CGPointMake(61.43, 29.59) controlPoint2: CGPointMake(53.78, 23.51)];
    [bezier7Path closePath];
    [color10 setFill];
    [bezier7Path fill];
}

+ (void)drawHomeUserButtonIcon
{
    //// Color Declarations
    UIColor* color10 = [UIColor colorWithRed: 0.333 green: 0.431 blue: 0.475 alpha: 1];

    //// Rectangle Drawing


    //// Bezier 3 Drawing
    UIBezierPath* bezier3Path = UIBezierPath.bezierPath;
    [bezier3Path moveToPoint: CGPointMake(44.3, 15.6)];
    [bezier3Path addCurveToPoint: CGPointMake(39.33, 16.69) controlPoint1: CGPointMake(42.52, 15.6) controlPoint2: CGPointMake(40.84, 15.99)];
    [bezier3Path addCurveToPoint: CGPointMake(32.4, 27.5) controlPoint1: CGPointMake(35.24, 18.57) controlPoint2: CGPointMake(32.4, 22.7)];
    [bezier3Path addCurveToPoint: CGPointMake(38.16, 37.69) controlPoint1: CGPointMake(32.4, 31.82) controlPoint2: CGPointMake(34.71, 35.61)];
    [bezier3Path addCurveToPoint: CGPointMake(28.2, 63.2) controlPoint1: CGPointMake(32.43, 42.08) controlPoint2: CGPointMake(28.4, 51.81)];
    [bezier3Path addLineToPoint: CGPointMake(61.8, 63.2)];
    [bezier3Path addCurveToPoint: CGPointMake(51.18, 37.21) controlPoint1: CGPointMake(61.6, 51.38) controlPoint2: CGPointMake(57.25, 41.34)];
    [bezier3Path addCurveToPoint: CGPointMake(56.2, 27.5) controlPoint1: CGPointMake(54.22, 35.06) controlPoint2: CGPointMake(56.2, 31.51)];
    [bezier3Path addCurveToPoint: CGPointMake(44.3, 15.6) controlPoint1: CGPointMake(56.2, 20.93) controlPoint2: CGPointMake(50.87, 15.6)];
    [bezier3Path closePath];
    [bezier3Path moveToPoint: CGPointMake(80, 45)];
    [bezier3Path addCurveToPoint: CGPointMake(45, 80) controlPoint1: CGPointMake(80, 64.33) controlPoint2: CGPointMake(64.33, 80)];
    [bezier3Path addCurveToPoint: CGPointMake(10, 45) controlPoint1: CGPointMake(25.67, 80) controlPoint2: CGPointMake(10, 64.33)];
    [bezier3Path addCurveToPoint: CGPointMake(30.87, 12.97) controlPoint1: CGPointMake(10, 30.7) controlPoint2: CGPointMake(18.58, 18.4)];
    [bezier3Path addCurveToPoint: CGPointMake(35.65, 11.26) controlPoint1: CGPointMake(32.41, 12.29) controlPoint2: CGPointMake(34.01, 11.72)];
    [bezier3Path addCurveToPoint: CGPointMake(45, 10) controlPoint1: CGPointMake(38.63, 10.44) controlPoint2: CGPointMake(41.76, 10)];
    [bezier3Path addCurveToPoint: CGPointMake(80, 45) controlPoint1: CGPointMake(64.33, 10) controlPoint2: CGPointMake(80, 25.67)];
    [bezier3Path closePath];
    [color10 setFill];
    [bezier3Path fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfTagNumberButtonWithTagNumber: (NSString*)tagNumber
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(80, 44), NO, 0.0f);
    [StyleKitName drawTagNumberButtonWithTagNumber: tagNumber];

    UIImage* imageOfTagNumberButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTagNumberButton;
}

+ (UIImage*)imageOfTagIconButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawTagIconButtonWithFrame: frame];

    UIImage* imageOfTagIconButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTagIconButton;
}

+ (UIImage*)imageOfHomeIconTagsButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawHomeIconTagsButtonWithFrame: frame];

    UIImage* imageOfHomeIconTagsButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfHomeIconTagsButton;
}

+ (UIImage*)imageOfHomeAutherIconButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawHomeAutherIconButtonWithFrame: frame];

    UIImage* imageOfHomeAutherIconButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfHomeAutherIconButton;
}

+ (UIImage*)imageOfTagImageButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawTagImageButtonWithFrame: frame];

    UIImage* imageOfTagImageButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfTagImageButton;
}

+ (UIImage*)imageOfRolesButtonWithFrame: (CGRect)frame rolesText: (NSString*)rolesText
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [StyleKitName drawRolesButtonWithFrame: frame rolesText: rolesText];

    UIImage* imageOfRolesButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfRolesButton;
}

@end
