//
//  StyleKitName.h
//  ProjectName
//
//  Created by 君赏 on 15/3/24.
//  Copyright (c) 2015 支付界. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Images
+ (UIImage*)homeIcon;
+ (UIImage*)homeIconSetting;
+ (UIImage*)hommIconUser;
+ (UIImage*)menu_list;

// Generated Images
+ (UIImage*)imageOfTagNumberButtonWithTagNumber: (NSString*)tagNumber;
+ (UIImage*)imageOfTagIconButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHomeIconTagsButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfHomeAutherIconButtonWithFrame: (CGRect)frame;

@end
