//
//  StyleKitName.h
//  ProjectName
//
//  Created by 君赏 on 15/3/18.
//  Copyright (c) 2015 支付界. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Images
+ (UIImage*)homeIcon;

// Drawing Methods
+ (void)drawCanvas1;

@end
