//
//  StyleKitName.m
//  ProjectName
//
//  Created by 君赏 on 15/3/24.
//  Copyright (c) 2015 支付界. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Cache

static UIImage* _homeIcon = nil;

static UIImage* _imageOfTagNumberButton = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Images

+ (UIImage*)homeIcon { return _homeIcon ?: (_homeIcon = [UIImage imageNamed: @"homeIcon"]); }

#pragma mark Drawing Methods

+ (void)drawTagNumberButton
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Variable Declarations
    NSString* tagNumber = @"122222";

    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(15, 7, 50, 30);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: rectangleRect cornerRadius: 15];
    [UIColor.grayColor setFill];
    [rectanglePath fill];
    UIFont* rectangleFont = [UIFont systemFontOfSize: UIFont.systemFontSize];
    [UIColor.whiteColor setFill];
    CGFloat rectangleTextHeight = [tagNumber sizeWithFont: rectangleFont constrainedToSize: CGSizeMake(CGRectGetWidth(rectangleRect), INFINITY) lineBreakMode: UILineBreakModeWordWrap].height;
    CGContextSaveGState(context);
    CGContextClipToRect(context, rectangleRect);
    [tagNumber drawInRect: CGRectMake(CGRectGetMinX(rectangleRect), CGRectGetMinY(rectangleRect) + (CGRectGetHeight(rectangleRect) - rectangleTextHeight) / 2, CGRectGetWidth(rectangleRect), rectangleTextHeight) withFont: rectangleFont lineBreakMode: NSLineBreakByWordWrapping alignment: NSTextAlignmentCenter];
    CGContextRestoreGState(context);
}

#pragma mark Generated Images

+ (UIImage*)imageOfTagNumberButton
{
    if (_imageOfTagNumberButton)
        return _imageOfTagNumberButton;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(80, 44), NO, 0.0f);
    [StyleKitName drawTagNumberButton];

    _imageOfTagNumberButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return _imageOfTagNumberButton;
}

#pragma mark Customization Infrastructure

- (void)setTagNumberButtonTargets: (NSArray*)tagNumberButtonTargets
{
    _tagNumberButtonTargets = tagNumberButtonTargets;

    for (id target in self.tagNumberButtonTargets)
        [target setImage: StyleKitName.imageOfTagNumberButton];
}


@end
