//
//  StyleKitName.h
//  ProjectName
//
//  Created by 君赏 on 15/3/24.
//  Copyright (c) 2015 支付界. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* tagNumberButtonTargets;

// Images
+ (UIImage*)homeIcon;

// Generated Images
+ (UIImage*)imageOfTagNumberButton;

@end
