//
//  StyleKitName.m
//  ProjectName
//
//  Created by 君赏 on 15/3/18.
//  Copyright (c) 2015 支付界. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Cache

static UIImage* _homeIcon = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Images

+ (UIImage*)homeIcon { return _homeIcon ?: (_homeIcon = [UIImage imageNamed: @"homeIcon"]); }

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
}

@end
